<template>
  <section class="graph-workbench">
    <button class="graph-toggle" @click="visible = !visible">Graph workbench</button>
    <aside v-if="visible" class="graph-panel">
      <header><div><small>SPATIAL KNOWLEDGE GRAPH</small><h2>Graph publishing workbench</h2></div><button @click="visible=false">×</button></header>
      <p class="active">Active: {{ graphStatus.version || 'Loading' }} · {{ graphStatus.source || 'bundled' }}</p>
      <div class="toolbar"><button @click="load" :disabled="busy">Refresh</button><button @click="loadSelected" :disabled="busy || !selected">Load</button><button @click="applyTemplate" :disabled="busy || !selected">Template</button><button @click="testIntents" :disabled="busy">Test intents</button></div>
      <label>Capability<select v-model="selected" @change="loadSelected"><option v-for="item in capabilities" :key="item.id" :value="item.id">{{ item.id }}</option></select></label>
      <label>Candidate version<input v-model="draft.version" placeholder="e.g. 1.3" /></label>
      <label>Aliases (one per line)<textarea v-model="aliases" rows="4" /></label>
      <label>Knowledge purpose<textarea v-model="purpose" rows="3" /></label>
      <label>Acceptance utterances (one per line)<textarea v-model="acceptanceText" rows="3" /></label>
      <label>Full candidate JSON<textarea v-model="draftText" rows="10" spellcheck="false" /></label>
      <div class="toolbar"><button @click="generateDraft" :disabled="busy">Generate JSON</button><button class="primary" @click="preview" :disabled="busy">Validate & preview</button></div>
      <div v-if="previewData" class="preview"><strong>{{ previewData.valid ? 'Quality gates passed' : 'Quality gates failed' }}: {{ previewData.preview?.version }}</strong><span v-for="change in previewData.preview?.changes" :key="change.capabilityId">{{ change.capabilityId }}: {{ changed(change) }} · {{ (change.impacts||[]).join(', ') }}</span><span v-for="gate in previewData.qualityGates" :key="`${gate.capabilityId}-${gate.name}`" :class="gate.passed ? 'gate-pass' : 'gate-fail'">{{ gate.passed ? '✓' : '×' }} {{ gate.capabilityId }} / {{ gate.message }}</span><button v-if="previewData.valid" class="publish" @click="publish" :disabled="busy">Publish & activate</button></div>
      <div class="tests" v-if="tests.length"><strong>Natural language checks</strong><div v-for="item in tests" :key="item.utterance" :class="item.matched ? 'pass' : 'fail'">{{ item.matched ? '✓' : '×' }} {{ item.utterance }}<small>{{ item.capabilityId || 'No match' }} {{ item.tool || '' }}</small></div></div>
      <div class="revisions"><strong>Published revisions</strong><div v-for="item in revisions" :key="item.version"><span>{{ item.version }}</span><small>{{ item.note || item.publishedAt }}</small><button @click="rollback(item.version)" :disabled="busy || item.version===graphStatus.version">Rollback</button></div></div>
      <p v-if="notice" :class="notice.error ? 'notice error' : 'notice'">{{ notice.text }}</p>
    </aside>
  </section>
</template>

<script setup>
import { computed, ref } from 'vue';
import axios from 'axios';

const visible = ref(false); const busy = ref(false); const capabilities = ref([]); const revisions = ref([]); const graphStatus = ref({});
const selected = ref(''); const aliases = ref(''); const purpose = ref(''); const acceptanceText = ref(''); const draft = ref({ version: '' }); const draftText = ref(''); const previewData = ref(null); const tests = ref([]); const notice = ref(null);
const templates = { urban_metrics:{aliases:'容积率\n建筑指标\nFAR',purpose:'计算范围内容积率、建筑密度与覆盖率。',tests:'计算容积率'}, skyline_analysis:{aliases:'天际线分析\n天际线\nskyline',purpose:'按方向统计建筑高度轮廓。',tests:'进行天际线分析'}, sunlight_analysis:{aliases:'日照分析\n日照与阴影筛查\n阴影分析\nsunlight',purpose:'筛查日照时窗和阴影影响。',tests:'日照与阴影筛查'}, flood_analysis:{aliases:'洪水分析\n内涝分析\n淹没分析\nflood',purpose:'结合 DEM、降雨和排水条件进行洪涝风险筛查。',tests:'洪水分析 80mm，24h，20年'} };
const current = computed(() => capabilities.value.find(item => item.id === selected.value));
const notify = (text, error=false) => { notice.value = { text, error }; };
const load = async () => { busy.value=true; try { const [caps, history] = await Promise.all([axios.get('/api/agent/capabilities'), axios.get('/api/agent/capabilities/revisions')]); capabilities.value=caps.data.capabilities||[]; graphStatus.value=caps.data.graph||{}; revisions.value=history.data.revisions||[]; if (!selected.value) selected.value=capabilities.value[0]?.id||''; loadSelected(); } catch (e) { notify(e.response?.data?.code || e.message, true); } finally { busy.value=false; } };
const loadSelected = () => { const item=current.value; if (!item) return; aliases.value=(item.aliases||[]).join('\n'); purpose.value=String(item.knowledge?.purpose||''); acceptanceText.value=templates[item.id]?.tests || (item.aliases||[])[0] || ''; previewData.value=null; };
const applyTemplate = () => { const template=templates[selected.value]; if (!template) return notify('No template for this capability',true); aliases.value=template.aliases; purpose.value=template.purpose; acceptanceText.value=template.tests; previewData.value=null; };
const graphObject = () => { const item=current.value; if (!item) throw new Error('Select a capability'); const edited={...item, aliases:aliases.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean), knowledge:{...(item.knowledge||{}), ...(purpose.value.trim()?{purpose:purpose.value.trim()}: {})}}; return {version:draft.value.version.trim(),capabilities:[edited]}; };
const generateDraft = () => { try { draftText.value=JSON.stringify(graphObject(),null,2); previewData.value=null; } catch(e) { notify(e.message,true); } };
const candidate = () => JSON.parse(draftText.value || JSON.stringify(graphObject()));
const acceptanceTests = () => ({[selected.value]:acceptanceText.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)});
const preview = async () => { busy.value=true; try { const graph=JSON.stringify(candidate()); previewData.value=(await axios.post('/api/agent/capabilities/candidates/preview',{graph,acceptanceTests:acceptanceTests()})).data; notify(previewData.value.valid ? 'Candidate passed quality gates.' : 'Candidate failed quality gates.',!previewData.value.valid); } catch(e) { previewData.value=null; notify(e.response?.data?.message || e.message,true); } finally { busy.value=false; } };
const publish = async () => { busy.value=true; try { const graph=JSON.stringify(candidate()); const result=(await axios.post('/api/agent/capabilities/publish',{graph,author:'graph-workbench',note:`Edited ${selected.value}`,acceptanceTests:acceptanceTests()})).data; graphStatus.value=result.active||{}; previewData.value=null; notify(`Published and activated ${result.revision?.version}`); await load(); } catch(e) { notify(e.response?.data?.message || e.message,true); } finally { busy.value=false; } };
const rollback = async version => { if (!window.confirm(`Rollback to ${version}?`)) return; busy.value=true; try { const result=(await axios.post(`/api/agent/capabilities/rollback/${encodeURIComponent(version)}`)).data; graphStatus.value=result.active||{}; notify(`Rolled back to ${version}`); await load(); } catch(e) { notify(e.response?.data?.message || e.message,true); } finally { busy.value=false; } };
const testIntents = async () => { busy.value=true; try { tests.value=(await axios.post('/api/agent/capabilities/test-intents',{utterances:['进行天际线分析','日照与阴影筛查','洪水分析 80mm，24h，20年','计算容积率']})).data.results||[]; } catch(e) { notify(e.response?.data?.message || e.message,true); } finally { busy.value=false; } };
const changed = value => ['aliasesChanged','dataRequirementsChanged','knowledgeChanged'].filter(key=>value[key]).map(key=>({aliasesChanged:'aliases',dataRequirementsChanged:'data requirements',knowledgeChanged:'knowledge'}[key])).join(', ');
</script>

<style scoped>
.graph-workbench{position:absolute;top:18px;right:18px;z-index:1400}.graph-toggle{border:1px solid #5cc9bf;border-radius:8px;background:#073a49;color:#c8fff5;padding:8px 12px;font-size:12px;cursor:pointer}.graph-panel{position:absolute;right:0;top:42px;width:360px;max-height:calc(100vh - 78px);overflow:auto;padding:16px;border:1px solid #286b75;border-radius:12px;background:#082432ee;color:#d5edf0;box-shadow:0 18px 46px #00131dcc;font-size:12px}.graph-panel header{display:flex;justify-content:space-between}.graph-panel header h2{margin:3px 0 12px;font-size:18px}.graph-panel header small{color:#62d8c8;letter-spacing:.1em}.graph-panel header button{border:0;background:transparent;color:#c9ecf0;font-size:24px;cursor:pointer}.active{margin:0 0 12px;color:#8fb3bd}.graph-panel label{display:block;margin:10px 0;color:#a7c5cc}.graph-panel input,.graph-panel select,.graph-panel textarea{box-sizing:border-box;display:block;width:100%;margin-top:4px;padding:7px;border:1px solid #356b74;border-radius:6px;background:#0d3443;color:#e2f7f8;font:12px Consolas,monospace}.toolbar{display:flex;gap:7px;margin:9px 0;flex-wrap:wrap}.toolbar button,.preview button,.revisions button{border:1px solid #487d85;border-radius:6px;background:#123f50;color:#d7f8f6;padding:6px 9px;cursor:pointer}.toolbar .primary,.publish{background:#49bba9!important;color:#032e32!important;border-color:#68e1cc!important}.preview,.tests,.revisions{display:grid;gap:6px;margin-top:13px;padding:10px;border:1px solid #285a64;border-radius:7px;background:#0a2b38}.preview span,.tests small,.revisions small{display:block;color:#8eabb2}.gate-pass{color:#8ce6be!important}.gate-fail{color:#ff9b9b!important}.tests .pass{color:#8ce6be}.tests .fail{color:#ff9b9b}.revisions>div{display:grid;grid-template-columns:1fr auto;gap:4px;align-items:center}.revisions small{grid-column:1}.revisions button{grid-column:2;grid-row:1/3}.notice{color:#8ce6be}.notice.error{color:#ff9b9b}@media(max-width:600px){.graph-panel{width:min(360px,calc(100vw - 36px))}}
</style>
